/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author Givaro
 */
public class AplikasiKalkulator extends javax.swing.JFrame {
    boolean zeroinit = true, counted = false;
    /**
     * Creates new form AplikasiKalkulator
     */
    public AplikasiKalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tujuhButton = new javax.swing.JButton();
        empatButton = new javax.swing.JButton();
        satuButton = new javax.swing.JButton();
        titikButton = new javax.swing.JButton();
        delapanButton = new javax.swing.JButton();
        limaButton = new javax.swing.JButton();
        duaButton = new javax.swing.JButton();
        nolButton = new javax.swing.JButton();
        sembilanButton = new javax.swing.JButton();
        enamButton = new javax.swing.JButton();
        tigaButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        tambahButton = new javax.swing.JButton();
        kurangButton = new javax.swing.JButton();
        kaliButton = new javax.swing.JButton();
        bagiButton = new javax.swing.JButton();
        hitungButton = new javax.swing.JButton();
        persenButton = new javax.swing.JButton();
        backspaceButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        layarTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Kalkulator");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));

        tujuhButton.setText("7");
        tujuhButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tujuhButtonActionPerformed(evt);
            }
        });

        empatButton.setText("4");
        empatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empatButtonActionPerformed(evt);
            }
        });

        satuButton.setText("1");
        satuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satuButtonActionPerformed(evt);
            }
        });

        titikButton.setText(".");
        titikButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titikButtonActionPerformed(evt);
            }
        });

        delapanButton.setText("8");
        delapanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delapanButtonActionPerformed(evt);
            }
        });

        limaButton.setText("5");
        limaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limaButtonActionPerformed(evt);
            }
        });

        duaButton.setText("2");
        duaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duaButtonActionPerformed(evt);
            }
        });

        nolButton.setText("0");
        nolButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nolButtonActionPerformed(evt);
            }
        });

        sembilanButton.setText("9");
        sembilanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sembilanButtonActionPerformed(evt);
            }
        });

        enamButton.setText("6");
        enamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enamButtonActionPerformed(evt);
            }
        });

        tigaButton.setText("3");
        tigaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tigaButtonActionPerformed(evt);
            }
        });

        clearButton.setText("C");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(titikButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nolButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(satuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(duaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tigaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(empatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tujuhButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delapanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sembilanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tujuhButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delapanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sembilanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(satuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tigaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titikButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nolButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        tambahButton.setText("+");
        tambahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahButtonActionPerformed(evt);
            }
        });

        kurangButton.setText("-");
        kurangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangButtonActionPerformed(evt);
            }
        });

        kaliButton.setText("*");
        kaliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaliButtonActionPerformed(evt);
            }
        });

        bagiButton.setText("/");
        bagiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagiButtonActionPerformed(evt);
            }
        });

        hitungButton.setText("=");
        hitungButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungButtonActionPerformed(evt);
            }
        });

        persenButton.setText("%");
        persenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persenButtonActionPerformed(evt);
            }
        });

        backspaceButton.setText("B");
        backspaceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backspaceButtonActionPerformed(evt);
            }
        });

        exitButton.setText("E");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(backspaceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(hitungButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(persenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(kaliButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bagiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tambahButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kurangButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kurangButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kaliButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bagiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hitungButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(persenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backspaceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        layarTF.setEditable(false);
        layarTF.setBackground(new java.awt.Color(255, 204, 204));
        layarTF.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(layarTF)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(layarTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    double hasil;
    String operandSatu = "", operator = "", operandDua = "";
    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        layarTF.setText("0");
        operandSatu = "";
        operandDua = "";
        operator = "";
        zeroinit = true;
    }//GEN-LAST:event_clearButtonActionPerformed

    private void satuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satuButtonActionPerformed
        if (counted) {
            layarTF.setText("1");
            counted = false;
        } else {
            if (layarTF.getText().equals("0")) {
                layarTF.setText("1");
            } else {
                layarTF.setText(layarTF.getText() + "1");
            }
        }
    }//GEN-LAST:event_satuButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        int reply = JOptionPane.showConfirmDialog(
                null,
                "Loh, Yakin Mau Keluar?",
                "Konfirmasi Keluar Aplikasi",
                JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitButtonActionPerformed

    private void nolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nolButtonActionPerformed
        if (counted) {
            layarTF.setText("0");
            counted = false;
        } else {
            if (layarTF.getText().equals("0")) {
                layarTF.setText("0");
            } else {
                layarTF.setText(layarTF.getText() + "0");
            }
        }
    }//GEN-LAST:event_nolButtonActionPerformed

    private void tambahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahButtonActionPerformed
        operandSatu = layarTF.getText();
        operator = "+";
        layarTF.setText("0");
    }//GEN-LAST:event_tambahButtonActionPerformed

    private void backspaceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backspaceButtonActionPerformed
        StringBuilder sb = new StringBuilder(layarTF.getText());
        sb.deleteCharAt(layarTF.getText().length() - 1);
        if(layarTF.getText().length() == 1) {
            layarTF.setText("0");
        } else {
            layarTF.setText(sb.toString());
        }
    }//GEN-LAST:event_backspaceButtonActionPerformed

    private void duaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duaButtonActionPerformed
        if (counted) {
            layarTF.setText("2");
            counted = false;
        } else {
            if (layarTF.getText().equals("0")) {
                layarTF.setText("2");
            } else {
                layarTF.setText(layarTF.getText() + "2");
            }
        }
    }//GEN-LAST:event_duaButtonActionPerformed

    private void hitungButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungButtonActionPerformed
        operandDua = layarTF.getText();
        Double doubleOperandSatu = Double.parseDouble(operandSatu);
        Double doubleOperandDua = Double.parseDouble(operandDua);
        if (!counted) {
            switch (operator) {
                case "+":
                    hasil = doubleOperandSatu + doubleOperandDua;
                    counted = true;
                    break;
                case "-":
                    hasil = doubleOperandSatu - doubleOperandDua;
                    counted = true;
                    break;
                case "*":
                    hasil = doubleOperandSatu * doubleOperandDua;
                    counted = true;
                    break;
                case "/":
                    hasil = doubleOperandSatu / doubleOperandDua;
                    counted = true;
                    break;
                default:
                    layarTF.setText("Invalid");
                    break;
            }
        } else {
            layarTF.setText(layarTF.getText());
        }
        if (Double.toString(hasil).contains(".0")) {
            layarTF.setText(Integer.toString((int) hasil));
        } else {
            layarTF.setText(Double.toString(hasil));
        }
    }//GEN-LAST:event_hitungButtonActionPerformed

    private void titikButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titikButtonActionPerformed
        if (counted) {
            layarTF.setText("0.");
            counted = false;
        } else {
            if (layarTF.getText().contains(".")) {
                layarTF.setText(layarTF.getText());
            } else {
                layarTF.setText(layarTF.getText() + ".");
            }
        }
    }//GEN-LAST:event_titikButtonActionPerformed

    private void persenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persenButtonActionPerformed
        operandDua = layarTF.getText();
        Double doubleOperandSatu = Double.parseDouble(operandSatu);
        Double doubleOperandDua = Double.parseDouble(operandDua);
        Double persenOperandDua = doubleOperandDua/100.0d;
        Double persenOperandDuaDenganSatu = doubleOperandSatu * persenOperandDua;
        
        if (!counted) {
            switch (operator) {
                case "+":
                    hasil = doubleOperandSatu + persenOperandDuaDenganSatu;
                    counted = true;
                    break;
                case "-":
                    hasil = doubleOperandSatu - persenOperandDuaDenganSatu;
                    counted = true;
                    break;
                case "*":
                    hasil = doubleOperandSatu * persenOperandDua;
                    counted = true;
                    break;
                case "/":
                    hasil = doubleOperandSatu / persenOperandDua;
                    counted = true;
                    break;
                default:
                    layarTF.setText("Invalid");
                    break;
            }       
        } else {
            layarTF.setText(layarTF.getText());
        }
        if (Double.toString(hasil).contains(".0")) {
            layarTF.setText(Integer.toString((int) hasil));
        } else {
            layarTF.setText(Double.toString(hasil));
        }
    }//GEN-LAST:event_persenButtonActionPerformed

    private void tigaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tigaButtonActionPerformed
        if (counted) {
            layarTF.setText("3");
            counted = false;
        } else {
            if (layarTF.getText().equals("0")) {
                layarTF.setText("3");
            } else {
                layarTF.setText(layarTF.getText() + "3");
            }
        }
    }//GEN-LAST:event_tigaButtonActionPerformed

    private void empatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empatButtonActionPerformed
        if (counted) {
            layarTF.setText("4");
            counted = false;
        } else {
            if (layarTF.getText().equals("0")) {
                layarTF.setText("4");
            } else {
                layarTF.setText(layarTF.getText() + "4");
            }
        }
    }//GEN-LAST:event_empatButtonActionPerformed

    private void limaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limaButtonActionPerformed
        if (counted) {
            layarTF.setText("5");
            counted = false;
        } else {
            if (layarTF.getText().equals("0")) {
                layarTF.setText("5");
            } else {
                layarTF.setText(layarTF.getText() + "5");
            }
        }
    }//GEN-LAST:event_limaButtonActionPerformed

    private void enamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enamButtonActionPerformed
        if (counted) {
            layarTF.setText("6");
            counted = false;
        } else {
            if (layarTF.getText().equals("0")) {
                layarTF.setText("6");
            } else {
                layarTF.setText(layarTF.getText() + "6");
            }
        }
    }//GEN-LAST:event_enamButtonActionPerformed

    private void tujuhButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tujuhButtonActionPerformed
        if (counted) {
            layarTF.setText("7");
            counted = false;
        } else {
            if (layarTF.getText().equals("0")) {
                layarTF.setText("7");
            } else {
                layarTF.setText(layarTF.getText() + "7");
            }
        }
    }//GEN-LAST:event_tujuhButtonActionPerformed

    private void delapanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delapanButtonActionPerformed
        if (counted) {
            layarTF.setText("8");
            counted = false;
        } else {
            if (layarTF.getText().equals("0")) {
                layarTF.setText("8");
            } else {
                layarTF.setText(layarTF.getText() + "8");
            }
        }
    }//GEN-LAST:event_delapanButtonActionPerformed

    private void sembilanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sembilanButtonActionPerformed
        if (counted) {
            layarTF.setText("9");
            counted = false;
        } else {
            if (layarTF.getText().equals("0")) {
                layarTF.setText("9");
            } else {
                layarTF.setText(layarTF.getText() + "9");
            }
        }
    }//GEN-LAST:event_sembilanButtonActionPerformed

    private void kurangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangButtonActionPerformed
        operandSatu = layarTF.getText();
        operator = "-";
        layarTF.setText("0");
    }//GEN-LAST:event_kurangButtonActionPerformed

    private void kaliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaliButtonActionPerformed
        operandSatu = layarTF.getText();
        operator = "*";
        layarTF.setText("0");
    }//GEN-LAST:event_kaliButtonActionPerformed

    private void bagiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagiButtonActionPerformed
        operandSatu = layarTF.getText();
        operator = "/";
        layarTF.setText("0");
    }//GEN-LAST:event_bagiButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiKalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backspaceButton;
    private javax.swing.JButton bagiButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton delapanButton;
    private javax.swing.JButton duaButton;
    private javax.swing.JButton empatButton;
    private javax.swing.JButton enamButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton hitungButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton kaliButton;
    private javax.swing.JButton kurangButton;
    private javax.swing.JTextField layarTF;
    private javax.swing.JButton limaButton;
    private javax.swing.JButton nolButton;
    private javax.swing.JButton persenButton;
    private javax.swing.JButton satuButton;
    private javax.swing.JButton sembilanButton;
    private javax.swing.JButton tambahButton;
    private javax.swing.JButton tigaButton;
    private javax.swing.JButton titikButton;
    private javax.swing.JButton tujuhButton;
    // End of variables declaration//GEN-END:variables
}
